<img src="<?php echo $this->getSkinUrl('pagaleve/images/pagaleve_logo.png'); ?>" width="125" /><br />
<strong><?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?></strong>
<br /><br />
<?php if ($this->getInfo()->getPagaleveCheckoutId() != '') : ?>
    <strong><?php echo $this->__('Pagaleve Checkout ID:'); ?></strong>
    <?php echo $this->htmlEscape($this->getInfo()->getPagaleveCheckoutId()); ?>
    <br /><br />
<?php endif; ?>
<?php if ($this->getInfo()->getPagalevePaymentId() != '') : ?>
    <strong><?php echo $this->__('Pagaleve Payment ID:'); ?></strong>
    <?php echo $this->htmlEscape($this->getInfo()->getPagalevePaymentId()); ?>
    <br /><br />
<?php endif; ?>
<?php if ($this->getInfo()->getPagaleveRefundId() != '') : ?>
    <strong><?php echo $this->__('Pagaleve Refund ID:'); ?></strong>
    <?php echo $this->htmlEscape($this->getInfo()->getPagaleveRefundId()); ?>
    <br /><br />
<?php endif; ?>