<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<?php if($this->getInfo()->getAdditionalData()): ?>
    <?php if($this->getPayableTo()): ?>
        <p><strong><?php echo $this->__('Make Check payable to:') ?></strong> <?php echo $this->escapeHtml($this->getPayableTo()) ?></p>
    <?php endif; ?>
    <?php if($this->getMailingAddress()): ?>
        <p><strong><?php echo Mage::helper('payment')->__('Send Check to:') ?></strong></p>
        <address class="checkmo-mailing-address">
            <?php echo nl2br($this->escapeHtml($this->getMailingAddress())) ?>
        </address>
    <?php endif; ?>
<?php endif; ?>
